config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'home/index'
  get '/bemvindo' => 'home#index'
  root 'home#index'
  
  resources :phones
  resources :addresses
  resources :contacts #, except: [:edit]
  resources :kinds
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact, optional: true

  validates :street, presence: true, length: { maximum: 50}
  validates :city, presence: true, length: { maximum: 50}
  validates :state, presence: true, length: { minimum: 2}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind, optional: true
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, length: { minimum: 3}
  validates :email, presence: true
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :contacts, dependent: :destroy

    validates :description, presence: true, length: { minimum: 3}
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact, optional: true

  validates :contact_id, presence: true
  validates :phone, presence: true, length: { minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]
  # http_basic_authenticate_with name: "root", password: "123", only: :destroy

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: t('message.create') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: t('message.update') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('message.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_options_for_select
      @kind_options_for_select = Kind.all
    end
    
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(
        :name, :email, :kind_id, :rmk, 
        address_attributes: [:street, :city, :state],
        phones_attributes:[:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all.order(:description).page(params[:page]).per(15)
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: t('message.create') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: t('message.update') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: t('message.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    ESTADOS_BRASILEIROS = [
        ["Acre", "AC"],
        ["Alagoas", "AL"],
        ["Amapá", "AP"],
        ["Amazonas", "AM"],
        ["Bahia", "BA"],
        ["Ceará", "CE"],
        ["Distrito Federal", "DF"],
        ["Espírito Santo", "ES"],
        ["Goiás", "GO"],
        ["Maranhão", "MA"],
        ["Mato Grosso", "MT"],
        ["Mato Grosso do Sul", "MS"],
        ["Minas Gerais", "MG"],
        ["Pará", "PA"],
        ["Paraíba", "PB"],
        ["Paraná", "PR"],
        ["Pernambuco", "PE"],
        ["Piauí", "PI"],
        ["Rio de Janeiro", "RJ"],
        ["Rio Grande do Norte", "RN"],
        ["Rio Grande do Sul", "RS"],
        ["Rondônia", "RO"],
        ["Roraima", "RR"],
        ["Santa Catarina", "SC"],
        ["São Paulo", "SP"],
        ["Sergipe", "SE"],
        ["Tocantins", "TO"]
    ]

    def options_for_states(selected)
        options_for_select(ESTADOS_BRASILEIROS, selected)
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true, class: :"dark-matter") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h3><%= "#{@contact.errors.count} #{t('message.error')} #{t('message.error_msg')}:" %></h3>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= form.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %>
      <%= address_fields.text_field :city %>
    </div>
      <div class="field">
      <%= address_fields.label :state %>
      <%= address_fields.select :state, options_for_states(@contact.address.state) %>
    </div>
  <% end %>

  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: {f: phones_fields} %>
    <% end %>
    <div class="field">
      <%= link_to_add_association('☎ Adicionar Telefone', form, :phones) %>
      <br>
      <br>
    </div>
  </div>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit t('buttons.save'), class: 'button' %>&nbsp;&nbsp;&nbsp;
    <%= link_to t('buttons.back'), contacts_path, class: 'button' %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
    <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "phone-field" %>
    <%= link_to_remove_association('remover', f) %>
    </div>
</div>

app/views/contacts/edit.html.erb
<div class="dark-matter">
    <h1><%= "#{t('title.edit')} #{@contact.model_name.human(count: 1)}" %></h1>
    <%= render 'form', contact: @contact %>
</div>

app/views/contacts/index.html.erb
<div class="dark-matter">
  <p id="notice"><%= notice %></p>

  <h1><%= "#{t('title.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  <table>
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name") %></th>
        <th><%= @contacts.model.human_attribute_name("kind") %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background: <%= cycle('#606060','#686868') %>">
          <td><%= contact.name %></td>
          <td><%= contact.kind.description %></td>
          <td class="action"><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td class="action"><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('message.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="page"><%= paginate @contacts %></div>
  <br>
  <div class="actions">
      <%= link_to "#{t('buttons.new')} #{@contacts.model.model_name.human(count: 1)}", new_contact_path, class: 'button' %>
      <%= link_to t('buttons.back'), bemvindo_path, class: 'button' %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="dark-matter">
    <h1><%= "#{t('title.new')} #{@contact.model_name.human(count: 1)}" %></h1>
    <%= render 'form', contact: @contact %>
</div>

app/views/home/index.html.erb
<div class="menu">
    <div class="bg"></div>
    <div class="bg2"></div>

    <div class="container">
        <div id="left" t>
            <h1>Seja bem-vindo!</h1>
            <p>Uma simples agenda de contatos escrita em Ruby Rails...</p>
        </div>

        <div id+"right">
            <ul>
                <li>
                    <img src=<%="#{image_url('attach_file-24px.svg')}" %> alt="icon">
                    <span>
                        <strong><%= link_to "TIPOS", kinds_path %></strong>
                        <p>Aqui você registra os tipos de contato...</p>
                    </span>
                </li>
                <li>
                    <img src=<%="#{image_url('contacts-24px.svg')}" %> alt="icon">
                    <span>
                        <strong><%= link_to "CONTATOS", contacts_path %></strong>
                        <p>Aqui você registra todos os seus contatos...</p>
                    </span>
                </li>
            </ul>
        </div>

    </div>
</div>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true, class: :"dark-matter") do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h3><%= "#{@kind.errors.count} #{t('message.error')} #{t('message.error_msg')}:" %></h3>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit t('buttons.save'), class: 'button' %>&nbsp;&nbsp;&nbsp;
    <%= link_to t('buttons.back'), kinds_path, class: 'button' %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<div class="dark-matter">
    <h1><%= "#{t('title.edit')} #{@kind.model_name.human(count: 1)}" %></h1>
    <%= render 'form', kind: @kind %>
</div>

app/views/kinds/index.html.erb
<div class="dark-matter">
  <p id="notice"><%= notice %></p>

  <h1><%= "#{t('title.listing')} #{@kinds.model.model_name.human(count: @kinds.count)}" %></h1>

  <table>
    <thead>
      <tr>
        <th><%= @kinds.model.human_attribute_name("description") %></th>
        <th colspan="3"></th>
      </tr style="background: <%= cycle('#606060','#686868') %>">
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr style="background: <%= cycle('#606060','#686868') %>">
          <td><%= kind.description %></td>
          <td class="action"><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
          <td class="action"><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('message.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="page"><%= paginate @kinds %></div>
  <br>
  <div class="actions">
      <%= link_to "#{t('buttons.new')} #{@kinds.model.model_name.human(count: 1)}", new_kind_path, class: 'button' %>
      <%= link_to t('buttons.back'), bemvindo_path, class: 'button' %>
  </div>
</div>

app/views/kinds/new.html.erb
<div class="dark-matter">
    <h1><%= "#{t('title.new')} #{@kind.model_name.human(count: 1)}" %></h1>
    <%= render 'form', kind: @kind %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    params[:controller] %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag params[:controller] %>
    <%#= javascript_include_tag 'alert' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>